autoML/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('process/',include('ml_core.urls', namespace='process')),
    path('', views.IndexView.as_view(), name='index'),
    path('logout-succes/', views.LogOutView.as_view(), name='success-logout'),
    path('login-succes/', views.LogInView.as_view(), name='success-login'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ml_core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
app_name= "ml_core"
urlpatterns = [
    path('create/', views.CreateProcess.as_view(), name='create-process'),
    path('<int:pk>/', views.DetailProcess.as_view(), name='process'),
    path('<int:pk>/update/', views.UpdateProcess.as_view(), name='update-process'),
    path('<int:pk>/delete/', views.DeleteProcess.as_view(), name='delete-process'),
    path('my-process/', views.ListProcesses.as_view(), name='list-process'),
    path('csv-list/', views.ListCSV.as_view(), name='list-csv'),
    path('csv/create/', views.CreateCSV.as_view(), name='create-csv'),
    path('csv/delete/<int:pk>', views.DeleteCSV.as_view(), name='delete-csv'),
    #path('execute/<str:model>/<str:machine>/<str:csv>/<str:target>/<int:test>', views.RPCRecieverTest.as_view(), name='execute'),
    path('execute/<int:pk>', views.RPCRecieverTest.as_view(), name='execute'),
    path('instance/create/', views.CreateInstance.as_view(), name='create-instance'),
    path('instance/delete/<int:pk>', views.DeleteInstance.as_view(), name='delete-instance'),
    path('instances/', views.ListInstances.as_view(), name='list-instance'),
    path('instance/update/<int:pk>', views.UpdateInstance.as_view(), name='update-instance'),
    path('model/create/', views.CreateModel.as_view(), name='create-model'),
    path('model/update/<int:pk>', views.UpdateModel.as_view(), name='update-model'),
    path('model/delete/<int:pk>', views.DeleteModel.as_view(), name='delete-model'),
    path('models/', views.ListModels.as_view(), name='list-model'),
]

ml_core/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from accounts.models import User
from django.utils import timezone
from django.db.models.signals import post_delete
from django.dispatch import receiver
import os
class Process(models.Model):
    title = models.CharField(max_length=250, blank=False, verbose_name='Title')
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, verbose_name='Creador', related_name='created_by')
    #slug = models.SlugField(allow_unicode=True, unique=True, blank=True)
    description = models.CharField(max_length=250, blank=True, verbose_name='Description')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    test = models.IntegerField()
    target = models.CharField(max_length=250, blank=False, verbose_name='Target')
    csv = models.ForeignKey("CSVFiles", on_delete=models.SET_NULL, blank=False, null=True, related_name='csv')
    categorical=models.CharField(max_length=250, blank=True, verbose_name='Categorical')
    model_binary = models.FileField(upload_to="model/", blank=True)
    model= models.ForeignKey("MLModel", on_delete=models.SET_NULL, blank=True, null=True, related_name='model')
    machine= models.ForeignKey("AwsInstance", on_delete=models.SET_NULL, blank=True, null=True, related_name='instance')

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('ml_core:process_list', kwargs={'slug':self.slug})

    class Meta:
        ordering=['created_at','updated_at']

class CSVFiles(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='uploaded_by')
    name = models.CharField(max_length=250, blank=False, verbose_name='name')
    file = models.FileField(upload_to="csv/")

    def save(self, *args, **kwargs):
        self.name= os.path.basename(self.file.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return os.path.basename(self.file.name)

@receiver(post_delete, sender=CSVFiles)
def submission_delete(sender, instance, **kwargs):
    '''
        Delete local file when deleting
    '''
    instance.file.delete(False)

class MLModel(models.Model):
    name = models.CharField(max_length=250, blank=False, unique=True, verbose_name='Name')
    def __str__(self):
        return self.name

class AwsInstance(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, blank=True, null=True, related_name='instances_from')
    name = models.CharField(max_length=250, blank=False, unique=True, verbose_name='Name')
    public_ip = models.CharField(max_length=250, blank=False, unique=True, verbose_name='ip')

    def __str__(self):
        return self.name
'''
class Configurations(models.Model):
    process = models.ForeignKey("Process", on_delete=models.SET_NULL, blank=True, null=True, related_name='process')
    configuration =

    def __str__(self):
        return (self.process.id+' '+self.model.name+' '+self.machine.name)

class Configuration(models.Model):
    model = models.ForeignKey("MLModel", on_delete=models.SET_NULL, blank=True, null=True, related_name='model')
    machine = models.ForeignKey("AwsInstance", on_delete=models.SET_NULL, blank=True, null=True, related_name='machine')
'''

ml_core/forms.py
from django import forms
from django.db import transaction
from .models import Process, CSVFiles

ml_core/views.py
from django.shortcuts import render, reverse, get_object_or_404
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView, RedirectView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Process, CSVFiles, AwsInstance, MLModel
from .rpc_client import MLRpcClient
import threading
import time
import paramiko
import os
import pickle
from queue import Queue
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
import xgboost as xgb
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error

class CreateProcess(LoginRequiredMixin, CreateView):
    model = Process
    fields = ('title', 'description', 'test', 'csv', 'model', 'machine', 'target', 'categorical')
    template_name='process/create_process.html'

    def get_success_url(self):
        return reverse('ml_core:list-process')

    def form_valid(self, form):
        '''
            Add user who creates the
            Add validation and execute process
        '''
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class UpdateProcess(LoginRequiredMixin,UpdateView):
    model = Process
    fields = ('title', 'description', 'test', 'csv', 'model', 'machine', 'target', 'categorical')
    template_name='process/update_process.html'
    def get_success_url(self):
        return reverse('ml_core:list-process')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)

class DeleteProcess(LoginRequiredMixin,DeleteView):
    model=Process
    success_url= reverse_lazy('ml_core:list-process')
    template_name='process/delete_process.html'
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)

class ListProcesses(LoginRequiredMixin,ListView):
    model=Process
    context_object_name='process_list'
    template_name='process/list_process.html'
    def get_queryset(self):
        '''
            Filter by user
        '''
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)
class DetailProcess(LoginRequiredMixin,DetailView):
    model=Process
    template_name='process/detail_process.html'

class ListCSV(LoginRequiredMixin,ListView):
    model=CSVFiles
    context_object_name='csv_list'
    template_name='process/list_csv.html'
    def get_queryset(self):
        '''
            Filter by user
        '''
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)

class CreateCSV(LoginRequiredMixin, CreateView):
    model = CSVFiles
    fields = ('file',)
    template_name='process/create_csv.html'

    def get_success_url(self):
        return reverse('ml_core:list-csv')

    def form_valid(self, form):
        '''
            Add user who creates the
            Add validation and execute process
        '''
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()

        return super().form_valid(form)

class DeleteCSV(LoginRequiredMixin,DeleteView):
    model=CSVFiles
    success_url= reverse_lazy('ml_core:list-csv')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)
'''
class CreateConfiguration(LoginRequiredMixin, CreateView):
    model = Configurations
    fields = ('process','model', 'machine')
    template_name='process/create_configuration.html'
'''
class CreateInstance(LoginRequiredMixin, CreateView):
    model = AwsInstance
    fields = ('name', 'public_ip')
    template_name='process/create_instance.html'

    def get_success_url(self):
        return reverse('ml_core:list-process')

    def form_valid(self, form):
        '''
            Add user who creates the
            Add validation and execute process
        '''
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        autostart(self.object.public_ip)
        self.object.save()
        print(self.object.public_ip)
        return super().form_valid(form)

class UpdateInstance(LoginRequiredMixin,UpdateView):
    model = AwsInstance
    fields = ('name','public_ip')
    template_name='process/update_instance.html'
    def get_success_url(self):
        return reverse('ml_core:list-instance')
    '''
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)
    '''
class DeleteInstance(LoginRequiredMixin,DeleteView):
    model=AwsInstance
    success_url= reverse_lazy('ml_core:list-instance')
    template_name='process/delete_instance.html'
    '''
    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)
    '''
class ListInstances(LoginRequiredMixin,ListView):
    model=AwsInstance
    context_object_name='instance_list'
    template_name='process/list_instances.html'
    '''
    def get_queryset(self):

            Filter by user

        queryset = super().get_queryset()
        return queryset.filter(user=self.request.user.id)
    '''
class CreateModel(LoginRequiredMixin, CreateView):
    model = MLModel
    fields = ('name',)
    template_name='process/create_model.html'

    def get_success_url(self):
        return reverse('ml_core:list-model')

class ListModels(LoginRequiredMixin,ListView):
    model=MLModel
    context_object_name='models'
    template_name='process/list_models.html'

class UpdateModel(LoginRequiredMixin,UpdateView):
    model = MLModel
    fields = ('name',)
    template_name='process/update_model.html'
    def get_success_url(self):
        return reverse('ml_core:list-model')

class DeleteModel(LoginRequiredMixin,DeleteView):
    model=MLModel
    success_url= reverse_lazy('ml_core:list-model')
    template_name='process/delete_model.html'


response=[]

class RPCRecieverTest(LoginRequiredMixin, TemplateView):
    template_name = "process/rpc.html"
    model=Process

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #context['model']=self.kwargs['model']
        #context['machine']=self.kwargs['machine']
        #print(type(self.kwargs['machine']))
        process= Process.objects.get(pk=self.kwargs['pk'])
        print(process.machine.public_ip)
        print(process.csv)
        queue=Queue()
        pd_csv=pd.read_csv(process.csv.file)
        thread1 = threading.Thread(target = execute_server_code, args = (process.machine.public_ip,))
        thread2 = threading.Thread(target = rpc, args = (process.model.name, pd_csv, process.target, process.test, process.categorical,queue,))

        thread1.start()
        thread2.start()
        thread2.join()
        thread1.join()
        task=queue.get()
        #task=response.pop()

        print(len(response))
        if task:
            print(type(task))
            task=pickle.loads(task)
            if task['model']!=-1:
                context['machine']=process.machine.name
                context['machine_ip']=process.machine.public_ip
                context['model']=process.model.name
                context['csv']=process.csv.name
                try:
                    context['message']=task['mse']
                except:
                    pass
                pickle.dump(task['model'], open('media/model/'+task['name']+".pkl", 'wb'))
                context['model_binary']='../../media/model/'+task['name']+".pkl"
                process.model_binary='model/'+task['name']+".pkl"
                process.save()
            else:
                context['error']="An error ocurred try using another model!"

        return context

def execute_server_code(machine):

    print('Conectando')
    ssh = paramiko.SSHClient()
    k=paramiko.RSAKey.from_private_key_file('ml_core/cluster1.pem')
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    print('Conectando')
    #ec2-184-72-96-38.compute-1.amazonaws.com
    ssh.connect(hostname=machine, username='ubuntu', pkey=k)
    print('Lanzando comando')
    #scp_command='scp -i ml_core/cluster1.pem media/csv/'+csv+' ubuntu@'+machine+':/home/ubuntu'
    #os.system(scp_command)
    ssh_stdin, ssh_stdout, ssh_stderr = ssh.exec_command("python3 rpc_server.py", get_pty=True, timeout=12.0)
    #time.sleep(2)
    ssh_stdin.flush()

    for line in iter(ssh_stdout.readline,""):
        print(line,end="")

    ssh.close()

def rpc(model, dataset, target, test, categorical, queue):

    #https://stackoverflow.com/questions/31834743/get-output-from-a-paramiko-ssh-exec-command-continuously/39231690#39231690
    ml_rpc = MLRpcClient()
    print(" [x] Requesting "+model)
    if model == 'svm':
        response = ml_rpc.call_svm(dataset, target, test, categorical)
    elif model == 'xgboost':
        response = ml_rpc.call_xgboost(dataset, target, test, categorical)
    elif model == 'logistic':
        response = ml_rpc.call_logistic(dataset, target, test, categorical)
    elif model == 'linear':
        response = ml_rpc.call_linear(dataset, target, test, categorical)
    print(" [.] Got %r" % response)
    queue.put(response)
    queue.task_done()
    return 1

def autostart(machine):
    print('Conectando')
    ssh = paramiko.SSHClient()
    k=paramiko.RSAKey.from_private_key_file('ml_core/cluster1.pem')
    ssh.set_missing_host_key_policy(paramiko.AutoAddPolicy())
    print('Conectando')
    ssh.load_host_keys(os.path.expanduser('~/.ssh/known_hosts'))
    ssh.connect(hostname=machine, username='ubuntu', pkey=k)
    print('Lanzando comando')

ml_core/templates/process/create_configuration.html
{%extends 'base.html'%}
{% block content %}

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="Submit" value="Create" class='btn btn-default'>
</form>
{% endblock %}

ml_core/templates/process/create_csv.html
{%extends 'base.html'%}
{% block content %}
<style>
  form{margin-top:5%;}
</style>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="Submit" value="Create" class='btn btn-primary'>
</form>
{% endblock %}

ml_core/templates/process/create_instance.html
{%extends 'base.html'%}
{% block content %}
<style>
  form{margin-top:5%;}
</style>

<form style="margin-top:5%" method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="Submit" value="Create" class='btn btn-primary'>
</form>
{% endblock %}

ml_core/templates/process/create_process.html
{%extends 'base.html'%}
{% block content %}
<style>
  p{font-size:20px}
  .form-group{margin-top:5%}
  </style>
<form method="post">
  <div class="form-group">
  {% csrf_token %}
  {{ form.as_p}}
  <input type="Submit" value="Create" class='btn btn-primary'>
</form>
{% endblock %}

ml_core/templates/process/delete_instance.html
{% extends 'base.html' %}
{% block content %}
<style>
  form{margin-top:5%;}
</style>

  <h1>Delete {{awsInstance.name}}</h1>
  <form method="post">
    {%csrf_token%}
  <input type="submit" class="btn btn-danger"value="Delete">
  <a href="{%url 'ml_core:list-instance'%}">Cancel</a>
  </form>

{% endblock %}

ml_core/templates/process/delete_process.html
{% extends 'base.html' %}
{% block content %}
<style>
  form{margin-top:5%;}
</style>

  <h1>Delete {{process.title}}</h1>
  <form method="post">
    {%csrf_token%}
  <input type="submit" class="btn btn-danger"value="Delete">
  <a href="{%url 'ml_core:process' pk=process.id %}">Cancel</a>
  </form>

{% endblock %}

ml_core/templates/process/detail_process.html
{%extends 'base.html'%}
{% block content %}


<div class="jumbotron">
  {%if user == process.user %}
  <h1 class="display-4">{{process.title}}</h1>
  <p>Descripcion: {{process.description}}</p>
  <p>Creator: {{process.user}}</p>
  <p>Creation hour: {{process.created_At}}</p>
  <p>Update hour: {{process.updated_at}}</p>
  <p>Test: {{process.test}}</p>
  <p>CSV: {{process.csv}}</p>
  <p>Model: {{process.model.name}}</p>

  <table>
    <tr>
      <td><a class="btn btn-warning" href="{% url 'ml_core:update-process' pk=process.id %}">Update</a></td>
      <td><a class="btn btn-danger" href="{% url 'ml_core:delete-process' pk=process.id %}">Delete</a></td>
      {%if process.model_binary %}
      <td><a class="btn btn-success" href="{{process.model_binary.url}}" download>Download</a></td>
      {% endif %}
    </tr>

  {% endif %}
  </table>
</div>

{% endblock %}

ml_core/templates/process/list_csv.html
{%extends 'base.html'%}
{% block content %}
<style>
  h1{margin-top:5%;text-align:center;}
  .create{text-align: center;
    font-size: 20px;
    margin-bottom: 2%;}

  </style>
<h1>My CSV Files</h1>

<a class="nav-link create" href="{%url 'ml_core:create-csv'%}">Create csv</a>

<div class="row">
  {% for csv in csv_list %}
    <div class="col-md-4 col-sm-12">
        <div class="card h-100 text-center">
          <div class="card-header h-100">
            <a href="{{csv.file.url}}" download><h5 class="card-title text-align">{{csv.name}}</h5></a>
            <form method="post" action="{% url 'ml_core:delete-csv' pk=csv.id %}">
              {%csrf_token%}
              <input type="submit" class="btn btn-danger"value="Delete">
            </form>
          </div>
        </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

ml_core/templates/process/list_model.html
{%extends 'base.html'%}
{% block content %}

<style>
  h1{margin-top:5%;text-align:center;}
  .create{text-align: center;
    font-size: 20px;
    margin-bottom: 2%;}
  table{margin-left:25%;}
  h5:nth-child(2){font-size:15px;}
  </style>

<h1>Available Models</h1>

<a class="nav-link create" href="{%url 'ml_core:create-model'%}">Create Model</a>

<div class="row">
  {% for model in models %}
    <div class="col-md-4 col-sm-12">
        <div class="card h-100 text-center">
          <div class="card-header h-100">
            <h5 class="card-title text-align">{{model.name}}</h5>
            <table>
              <tr>
                <td><a class="btn btn-warning" href="{% url 'ml_core:update-model' pk=instance.id %}">Update</a></td>
                <td><a class="btn btn-danger" href="{% url 'ml_core:delete-model' pk=instance.id %}">Delete</a></td>
              </tr>
            </table>
          </div>
        </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

ml_core/templates/process/list_process.html
{%extends 'base.html'%}
{% block content %}

<style>
  h1{margin-top:5%;text-align:center;}
  .create{text-align: center;
    font-size: 20px;
    margin-bottom: 2%;}

  </style>

<h1>My processes</h1>

<a class="nav-link create" href="{%url 'ml_core:create-process'%}">Create process</a>

<div class="row">
  {% for process in process_list %}
    <div class="col-md-4 col-sm-12">
        <div class="card h-100 text-center">
          <div class="card-header h-100">
            <h5 class="card-title text-align"><a href="{%url 'ml_core:process' pk=process.id%}">{{process.title}}</a></h5>
            <a class="btn btn-success" href="{% url 'ml_core:execute' pk=process.id%}">Execute</a>
          </div>
        </div>
    </div>
  {% endfor %}
</div>
{% endblock %}

ml_core/templates/process/rpc.html
{% extends 'base.html' %}
{% block content %}
<style>
  form{margin-top:5%;}
</style>
<h1 class="checkout text-danger" >{{error}} </h1>
{%if model%}
  <h1 class="checkout">Modelo: {{model}} </h1>
  <h1 class="checkout">CSV: {{csv}} </h1>
  <h1 class="checkout">Máquina: {{machine}}</h1>
  <h4 class="checkout">Ip: {{machine_ip}} </h4>
  {%if message%}
  <p>Score: {{message}}</p>
  {%endif%}
  <a class="btn btn-success" href="{{model_binary}}" download>Download</a>
{%endif%}




{% endblock %}

ml_core/templates/process/update_instance.html
{%extends 'base.html'%}
{% block content %}

<style>
  form{margin-top:5%;}
</style>


<form method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <input class="btn btn-warning" type="Submit" value="Update" class='btn btn-default'>
</form>
{% endblock %}

ml_core/templates/process/update_model.html
{%extends 'base.html'%}
{% block content %}

<style>
  form{margin-top:5%;}
</style>

{% if user.is_superuser %}
<form method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <input class="btn btn-warning" type="Submit" value="Update" class='btn btn-default'>
</form>
{% endif %}
{% endblock %}

ml_core/templates/process/update_process.html
{%extends 'base.html'%}
{% block content %}

<style>
  form{margin-top:5%;}
</style>

<form method="post">
  {% csrf_token %}
  {{ form.as_p}}
  <input class="btn btn-warning" type="Submit" value="Update" class='btn btn-default'>
</form>
{% endblock %}