accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
app_name= 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('change-password', auth_views.PasswordChangeView.as_view(template_name='accounts/change_password.html', success_url=reverse_lazy("success-login")), name='change-password'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

autoML/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('process/',include('ml_core.urls', namespace='process')),
    path('', views.IndexView.as_view(), name='index'),
    path('logout-succes/', views.LogOutView.as_view(), name='success-logout'),
    path('login-succes/', views.LogInView.as_view(), name='success-login'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ml_core/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
app_name= "ml_core"
urlpatterns = [
    path('create/', views.CreateProcess.as_view(), name='create-process'),
    path('<int:pk>/', views.DetailProcess.as_view(), name='process'),
    path('<int:pk>/update/', views.UpdateProcess.as_view(), name='update-process'),
    path('<int:pk>/delete/', views.DeleteProcess.as_view(), name='delete-process'),
    path('my-process/', views.ListProcesses.as_view(), name='list-process'),
    path('csv-list/', views.ListCSV.as_view(), name='list-csv'),
    path('csv/create/', views.CreateCSV.as_view(), name='create-csv'),
    path('csv/delete/<int:pk>', views.DeleteCSV.as_view(), name='delete-csv'),
    #path('execute/<str:model>/<str:machine>/<str:csv>/<str:target>/<int:test>', views.RPCRecieverTest.as_view(), name='execute'),
    path('execute/<int:pk>', views.RPCRecieverTest.as_view(), name='execute'),
    path('instance/create/', views.CreateInstance.as_view(), name='create-instance'),
    path('instance/delete/<int:pk>', views.DeleteInstance.as_view(), name='delete-instance'),
    path('instances/', views.ListInstances.as_view(), name='list-instance'),
    path('instance/update/<int:pk>', views.UpdateInstance.as_view(), name='update-instance'),
    path('model/create/', views.CreateModel.as_view(), name='create-model'),
    path('model/update/<int:pk>', views.UpdateModel.as_view(), name='update-model'),
    path('model/delete/<int:pk>', views.DeleteModel.as_view(), name='delete-model'),
    path('models/', views.ListModels.as_view(), name='list-model'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  </head>
  <style>
  a p:hover{color:#007bff}
  </style>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <a style="font-family:unset; font-size:30px;" class="navbar-brand" href="{% url 'ml_core:list-process' %}"><p>autoML</p></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <ul class="navbar-nav justify-content-end">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ml_core:list-csv' %}">Datasets</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ml_core:list-instance' %}">Instances</a>
          </li>
          {% if user.is_superuser %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'ml_core:list-model' %}">Models</a>
          </li>
          {% endif %}
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-toggle="dropdown" aria-haspopup="true" href="#" aria-expanded="false">{{user.username}}</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{%url 'admin:index'%}">Admin</a>
              <a class="dropdown-item" href="{% url 'accounts:change-password' %}" >Change Password</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{%url 'accounts:logout'%}">Log Out</a>

            </div>
          </li>
          {% else %}

          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
          </li>
          {% endif %}

          <li>
          </li>
        </ul>
      </div>
    </nav>
    <div class="container content">
      {% block content %}
      {% endblock %}
    </div>



  </body>
</html>

templates/index.html
{%extends 'base.html'%}
{% block content %}
  <h1>LOGG IN or Sign Up</h1>
{% endblock %}

templates/success_login.html
{%extends 'base.html'%}
{% block content %}
  {% if user.is_authenticated %}
    <h1>Bienvenido {{user.username}}</h1>
  {%else %}
    <h1>Error</h1>
  {%endif%}
{% endblock %}

templates/success_logout.html
{%extends 'base.html'%}
{% block content %}

    <h1>Nos vemos pronto</h1>

{% endblock %}